version: '3.6'
services:
  goapp:
    build: .
#      context: ./
#      dockerfile: Dockerfile
    restart: always
    hostname: goapphost
    container_name: goapphost
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: fluentd
    depends_on:
      - redisdb
    ports:
      - 8079:8080
    command: /shortener
    networks:
      - elasticsearch
#        ipv4_address: 172.16.238.2
#      default:
  redisdb:
    image: redis:alpine
    restart: always
    hostname: redisdbhost
    container_name: redisdbhost
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: fluentd
    volumes:
      - /opt/yevgen/docker_share/redis2/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - /opt/yevgen/docker_share/redis2/data:/data
    ports:
      - 6378:6379
    # command: ["redis-cli"]
    networks:
      - elasticsearch
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8088:80
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: fluentd
    networks:
      - elasticsearch
  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    volumes:
      -  /opt/yevgen/docker_share/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.9.2
    container_name: apm-server
    volumes:
      - /opt/yevgen/docker_share/apm_elastic/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - "8200:8200"
    networks:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/yevgen/docker_share/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticsearch
  kibana:
    image: kibana:7.9.2
    platform: linux/x86_64
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - /opt/yevgen/docker_share/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch
networks:
  elasticsearch: